#!/usr/bin/env bash

NAME=$1
FLAG=$2

if [ -z "$NAME" ]; then
  echo "❌ Error:Provide the file name"
  exit 1
fi

OUTPUT_NAME="${NAME%.*}"

if [ "$FLAG" == "-s" ]; then
  gcc -Wall -g -Werror -fsanitize=address,undefined "$NAME" -o "$OUTPUT_NAME"

  if [ $? -eq 0 ]; then
    echo "✅ Build sucessful! Running with AddressSanitizer....."
    echo "-----------------------------------------"

    ./"$OUTPUT_NAME"

    echo ""
    echo "_________________________________________"

    rm "$OUTPUT_NAME"
    rm -rf "$OUTPUT_NAME.dSYM"
    echo "🧹 Clean up!"
  else
    echo "❌ compilation failed 😢"
  fi

else
  gcc -Wall -g -Werror "$NAME" -o "$OUTPUT_NAME"

  if [ $? -eq 0 ]; then
    echo "✅ Build sucessful! Running....."
    echo "-----------------------------------------"

    leaks -atExit -- ./"$OUTPUT_NAME" 2>/dev/null

    echo ""
    echo "_________________________________________"

    rm "$OUTPUT_NAME"
    rm -rf "$OUTPUT_NAME.dSYM"
    echo "🧹 Clean up!"
  else
    echo "❌ compilation failed 😢"
  fi
fi
